In [8]:
df = pd.DataFrame({'name':['jim','jim','jim','jim','jim'],
               'number':['1','1','.','1','1']})

df['number'] = df['number'].str.replace(r'\D', '')

df

/var/folders/bg/jv0b8cmn4hq1x2msdj1mflq9dy7c1d/T/ipykernel_56548/2950407599.py:3: FutureWarning: The default value of regex will change from True to False in a future version.
  df['number'] = df['number'].str.replace(r'\D', '')

  name number
0  jim      1
1  jim      1
2  jim
3  jim      1
4  jim      1

In [4]:
import datetime
import numpy as np
import pandas as pd
import warnings

warnings.simplefilter(action='ignore', category=UserWarning)

#set dataframe display options 
pd.options.display.max_columns = 200
pd.options.display.max_rows = 200

#read in necessary sheets 
df = pd.read_excel('/Users/canderson/Documents/Python/Behavior-Psychology-Visualization-Tool/data/DP Beh Data 2022-23.xlsm', sheet_name = 'Feb', skiprows=[1,2])
dfyr = pd.read_excel('/Users/canderson/Documents/Python/Behavior-Psychology-Visualization-Tool/data/DP Beh Data 2022-23.xlsm', sheet_name = 'YiVis')

df.head(10)

,February,Unnamed: 1,Unnamed: 2,Unnamed: 3,Aggression,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Self Mutilation,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,SIB,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Disruptive,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66,Unnamed: 67,Unnamed: 68,Unnamed: 69,Unnamed: 70,Unnamed: 71,Unnamed: 72,Unnamed: 73,Unnamed: 74,Unnamed: 75,Insert,Unnamed: 77,Unnamed: 78,Unnamed: 79,Unnamed: 80,Unnamed: 81,Unnamed: 82,Unnamed: 83,Unnamed: 84,Unnamed: 85,Unnamed: 86,Unnamed: 87,Unnamed: 88,Unnamed: 89,Unnamed: 90,Unnamed: 91,Unnamed: 92,Unnamed: 93,Unnamed: 94,Bite Rel,F-Arm Catch,F-Choke Windmill,B-Choke,F-Hair Stab/Rel,B-Hair Stab/Rel,Deflection,Bite prevention,Front hair Pull Stab,Touch,Block Punch,1 Escort,2 Escort,2 Removal,1 E Seat Var,2 E Seat Var,Stand Wrap,One Arm Release,Mitts wear,Splints wear,Stuck/Combo,Frozen,Pacing
0,1,7-3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,3-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,11-7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2,7-3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,3-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,11-7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,3,7-3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,3-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,11-7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,4,7-3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [93]:
dfyr.head()

  Yi Han Data Visualization Tool Specs             Unnamed: 1
0                                  NaN                    NaN
1                            VersionID  Clinical_Behavior_v08
2                                  NaN                    NaN
3                           SchoolYear              2022-2023
4                                  NaN                    NaN

In [94]:
#get years variable 
year = dfyr.iloc[3,1]
year1, year2 = str.split(year, '-')
print(year)
print(year1)
print(year2)

2022-2023
2022
2023

In [95]:
#select necessary columns and front fill NaNs in month column 
dfbeh = df.iloc[:, [0,1,2,4,7,22,25,40,43,58,61,76,79]]
dfbeh = dfbeh.rename(columns = {'Unnamed: 1':'Shift','Unnamed: 2':'No Data','Unnamed: 7':dfbeh.columns[3]+'_beh','Unnamed: 25':dfbeh.columns[5]+'_beh',
                                'Unnamed: 43':dfbeh.columns[7]+'_beh','Unnamed: 61':dfbeh.columns[9]+'_beh','Unnamed: 79':dfbeh.columns[11]+'_beh'})
dfbeh.iloc[:,0] = dfbeh.iloc[:,0].fillna(method='ffill')
print(dfbeh.shape)
dfbeh.head()

(104, 13)

,February,Shift,No Data,Aggression,Aggression_beh,Self Mutilation,Self Mutilation_beh,SIB,SIB_beh,Disruptive,Disruptive_beh,Insert,Insert_beh
0,1,7-3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,3-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,11-7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2,7-3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2,3-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [96]:
#create 'month number' variable 
month_name = dfbeh.columns[0]
datetime_object = datetime.datetime.strptime(month_name, "%B")
month_num = datetime_object.month
print(month_num)

2

In [97]:
#if month number is between 7 and 12 year1 is selected, else year2 
if 7 <= month_num <= 12:
    year_num = year1
else:
    year_num = year2
print(year_num)

2023

In [98]:
#create date string 
date = str(year_num) + '-' + str(month_num)
date

'2023-2'

In [99]:
#create list of colum indexes for behavior data 
beh_indexes = [4,6,8,10,12]
print(month_num)
#loop through behavior indexes and create dataframes for each behavior 
behdfs = []
for i, bidx in enumerate(beh_indexes):
    #create new var for each df 
    beh_id = f"beh{i+1}" 
    #create long format df for behavior and drop unnecessary rows 
    beh_id = pd.melt(dfbeh, id_vars = [dfbeh.columns[0],dfbeh.columns[1],dfbeh.columns[2]],value_vars =[dfbeh.columns[bidx]])
    beh_id = beh_id.drop(beh_id.index[np.where(beh_id.index >= 93)])
    #filter for months that are less than 31 days 
    if month_num == 4 or month_num == 6 or month_num == 9 or month_num == 11:
        beh_id = beh_id.drop(beh_id.index[np.where(beh_id.index >= 90)])
    elif month_num ==2:
        beh_id = beh_id.drop(beh_id.index[np.where(beh_id.index >= 84)])
    else:
        beh_id = beh_id
    #add dfs to list 
    behdfs.append(beh_id)

#cocatanate into one lare dataframe, drop unnecessary rows
behs = pd.concat(behdfs)
behs = behs[~behs['variable'].isin(['Insert_beh'])]
#tidy up variable names and reset index
behs['variable'] = behs['variable'].str.replace(r'_beh', '')
behs.reset_index(drop = True,inplace=True)
#create date column and convery to padas datetime
behs['Date'] = date + '-' + behs.iloc[:,0].astype(str)
behs['Date'] = pd.to_datetime(behs['Date'])
behs.head()

2

  February Shift  No Data    variable  value       Date
0        1   7-3      NaN  Aggression    NaN 2023-02-01
1        1  3-11      NaN  Aggression    NaN 2023-02-01
2        1  11-7      NaN  Aggression    NaN 2023-02-01
3        2   7-3      NaN  Aggression    NaN 2023-02-02
4        2  3-11      NaN  Aggression    NaN 2023-02-02

In [100]:
#define a function encapsulting above code so that we can get data for one month
def get_month_dataframe(workbook_xl, month):
    #set dataframe display options 
    pd.options.display.max_columns = 200
    pd.options.display.max_rows = 200

    #read in necessary sheets 
    df = pd.read_excel(workbook_xl, sheet_name=month, skiprows=[1,2])
    dfyr = pd.read_excel(workbook_xl, sheet_name=0)

    #get years variable 
    year = dfyr.iloc[3,1]
    year1, year2 = str.split(year, '-')

    #select necessary columns and front fill NaNs in month column 
    dfbeh = df.iloc[:, [0,1,2,4,7,22,25,40,43,58,61,76,79]]
    dfbeh = dfbeh.rename(columns = {'Unnamed: 1':'Shift','Unnamed: 2':'No Data','Unnamed: 7':dfbeh.columns[3]+'_beh','Unnamed: 25':dfbeh.columns[5]+'_beh',
                                    'Unnamed: 43':dfbeh.columns[7]+'_beh','Unnamed: 61':dfbeh.columns[9]+'_beh','Unnamed: 79':dfbeh.columns[11]+'_beh'})
    dfbeh.iloc[:,0] = dfbeh.iloc[:,0].fillna(method='ffill')

    #create 'month number' variable 
    month_name = dfbeh.columns[0]
    datetime_object = datetime.datetime.strptime(month_name, "%B")
    month_num = datetime_object.month

    #if month number is between 7 and 12 year1 is selected, else year2 
    if 7 <= month_num <= 12:
        year_num = year1
    else:
        year_num = year2

    #create date string 
    date = str(year_num) + '-' + str(month_num)

    #create list of colum indexes for behavior data 
    beh_indexes = [4,6,8,10,12]

    #loop through behavior indexes and create dataframes for each behavior 
    behdfs = []
    for i, bidx in enumerate(beh_indexes):
        #create new var for each df 
        beh_id = f"beh{i+1}" 
        #create long format df for behavior and drop unnecessary rows 
        beh_id = pd.melt(dfbeh, id_vars = [dfbeh.columns[0],dfbeh.columns[1],dfbeh.columns[2]],value_vars =[dfbeh.columns[bidx]])
        beh_id = beh_id.drop(beh_id.index[np.where(beh_id.index >= 93)])
        if month_num == 4 or month_num == 6 or month_num == 9 or month_num == 11:
            beh_id = beh_id.drop(beh_id.index[np.where(beh_id.index >= 90)])
        elif month_num ==2:
            beh_id = beh_id.drop(beh_id.index[np.where(beh_id.index >= 84)])
        else:
            beh_id = beh_id
        #add dfs to list 
        behdfs.append(beh_id)

    #cocatanate into one lare dataframe, drop unnecessary rows 
    behs = pd.concat(behdfs)
    behs = behs[~behs['variable'].isin(['Insert_beh'])]
    #tidy up variable names and reset index
    behs['variable'] = behs['variable'].str.replace(r'_beh', '')
    behs.reset_index(drop = True,inplace=True)
    #create date column and convery to padas datetime
    behs['Date'] = date + '-' + behs.iloc[:,0].astype(str)
    behs['Date'] = pd.to_datetime(behs['Date'])
    #get the name of the first column, which we drop
    month_to_remove = behs.columns[0]
    return behs.drop(month_to_remove, axis=1)

#aggregates all months data into a single data frame
def get_all_months():
    months = ['July', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'June']
    xl_file = pd.ExcelFile('data/DP Beh Data 2022-23.xlsm')
    months_data = []
    for month in months:
        months_data.append(get_month_dataframe(xl_file, month))
    return pd.concat(months_data)


df_all_months = get_all_months()
print(df_all_months.shape)
df_all_months.head()

(4380, 5)

  Shift       No Data    variable  value       Date
0   7-3           NaN  Aggression    2.0 2022-07-01
1  3-11  No Behaviors  Aggression    0.0 2022-07-01
2  11-7  No Behaviors  Aggression    0.0 2022-07-01
3   7-3  No Behaviors  Aggression    0.0 2022-07-02
4  3-11  No Behaviors  Aggression    0.0 2022-07-02

In [6]:
import datetime
import numpy as np
import pandas as pd
import warnings

workbook_xl = pd.ExcelFile("/Users/yn/Documents/tcfd/visualization tool/Behavior Psychology Visualization Tool/data/DP Beh Data 2021-22.xlsm")
df = pd.read_excel(workbook_xl, sheet_name="MEDICATIONS", skiprows=[0])
df.head(10)

,Lithium,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Propranolol,...,Unnamed: 80,Insert Medication 10,Unnamed: 82,Unnamed: 83,Unnamed: 84,Unnamed: 85,Unnamed: 86,Unnamed: 87,Unnamed: 88,Unnamed: 89
0,Dose,unit/xDay (mg ml etc),START DATE,NaN,NaN,END DATE,NaN,NaN,Comments,Dose,...,Comments,Dose,unit (mg ml etc),START DATE,NaN,NaN,END DATE,NaN,NaN,Comments
1,NaN,NaN,MM,DD,YYYY,MM,DD,YYYY,NaN,NaN,...,NaN,NaN,NaN,MM,DD,YYYY,MM,DD,YYYY,NaN
2,1200,mg,07,01,2021,03,04,2022,NaN,540,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1050,mg,03,05,2022,03,16,2022,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,900,mg,03,17,2022,04,19,2022,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,750,mg,04,20,2022,06,07,2022,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,600,mg,06,08,2022,06,30,2022,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [71]:
workbook_xl = pd.ExcelFile("/Users/yn/Documents/tcfd/visualization tool/Behavior Psychology Visualization Tool/data/DP Beh Data 2021-22.xlsm")
df_meds = pd.read_excel(workbook_xl, sheet_name="MEDICATIONS", skiprows=[0, 3])
med_name = df_meds.columns[0]
df_meds = df_meds.drop(index=0)
pd.DataFrame(df_meds.iloc[:,0])

                                              Lithium
1                                                1200
2                                                1050
3                                                 900
4                                                 750
5                                                 600
6                                                 NaN
7                                                 NaN
8                                                 NaN
9                                                 NaN
10                                                NaN
11                                                NaN
12                                                NaN
13                                                NaN
14                                                NaN
15                                                NaN
16                                                NaN
17                                                NaN
18                                                NaN
19                                                NaN
20                                                NaN
21                                                NaN
22                                                NaN
23                                                NaN
24                                                NaN
25                                                NaN
26                                                NaN
27                                                NaN
28                                                NaN
29  Place a * to indicate medications tracked but ...
30  ** All dates will indicate the date of med adm...